server:
   port: 9000

spring:
   application:
      name: blog-config
   cloud:
      config:
         server:
            git:
               default-label: main              
               uri: https://github.com/1079368619/config
               search-paths: /CZ21-S3-Ply-blog
               username: 
               password: 
      
eurek:
   client:
      serviceUrl: 
         defaultZone: http://127.0.0.1:8000/eureka
