server:
   port: 80

spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql:127.0.0.1/CZ21-S3-Ply-favorite
      username: root
      password: a
      

mybatis:
   configuration:
      mapUnderscoreToCamelCase: true


logging:
   level:
      com:
         yc:
            favorite:
               dao: debug
               web: warn